version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  setup:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Build library
          command: yarn build:lib
      - run:
          name: Build documentation page
          command: yarn build:docs
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Build library
          command: yarn build:lib
      - run:
          name: Run all tests with coverage
          command: yarn test:coverage-ci
      - codecov/upload:
          file: ./packages/ui/coverage/coverage-final.json
      - codecov/upload:
          file: ./packages/form/coverage/coverage-final.json
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - setup
          filters:
            branches:
              ignore: gh-pages
